import {useEffect, Suspense} from "react";
import Head from "next/head";
import {str_replace} from "../../../helper/php.helper";
import Container from "../../../layouts/deskop/Container";
import BootStrapModal from "../../../elements/modal";


const About = (data = {}) => {

    useEffect(() => {
        require("bootstrap/dist/js/bootstrap.bundle.min.js");
    }, []);

    function Loading() {
        return <h2>🌀 Loading...</h2>;
    }

    return (
        <>
            <Container>
                <Head>
                    <title>About - ArdorNext</title>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <div className="px-4 pt-5 my-5 text-center border-bottom">
                    <h1 className="display-4 fw-bold">Centered screenshot</h1>
                    <div className="col-lg-6 mx-auto">
                        <p className="lead mb-4">Quickly design and customize responsive mobile-first sites with
                            Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables
                            and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript
                            plugins.</p>
                        <div className="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
                            <button type="button" className="btn btn-primary btn-lg px-4 me-sm-3">Primary button
                            </button>
                            <button type="button" className="btn btn-outline-secondary btn-lg px-4">Secondary</button>
                        </div>
                    </div>
                    <div className="overflow-hidden" style={{'max-height': '30vh'}}>
                        <div className="container px-5">
                            <img src="/site/images/bootstrap-docs.png"
                                 className="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image" width="700"
                                 height="500" loading="lazy"/>
                        </div>
                    </div>
                </div>
                <Suspense fallback={<Loading />}>
                    <div className="container col-xxl-8 px-4 py-5">
                        <div className="row flex-lg-row-reverse align-items-center g-5 py-5">
                            <div className="col-10 col-sm-8 col-lg-6">
                                <img src="/site/images/bootstrap-docs.png" className="d-block mx-lg-auto img-fluid"
                                     alt="Bootstrap Themes" width="700" height="500" loading="lazy"/>
                            </div>
                            <div className="col-lg-6">
                                <h1 className="display-5 fw-bold lh-1 mb-3">Responsive left-aligned hero with image</h1>
                                <p className="lead">Quickly design and customize responsive mobile-first sites with
                                    Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass
                                    variables and mixins, responsive grid system, extensive prebuilt components, and
                                    powerful JavaScript plugins.</p>
                                <div className="d-grid gap-2 d-md-flex justify-content-md-start">
                                    <button type="button" className="btn btn-primary btn-lg px-4 me-md-2">Primary</button>
                                    <button type="button" className="btn btn-outline-secondary btn-lg px-4">Default</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </Suspense>



                <BootStrapModal modalID="exampleModal" modalTitle="Contact Now Modal" modalAttribute={{size:'sm',buttonClass:'btn btn-primary'}}>
                    <form>
                        <div className="mb-3">
                            <label htmlFor="recipient-name" className="col-form-label">Recipient:</label>
                            <input type="text" className="form-control" id="recipient-name" />
                        </div>
                        <div className="mb-3">
                            <label htmlFor="message-text" className="col-form-label">Message:</label>
                            <textarea className="form-control" id="message-text"></textarea>
                        </div>
                    </form>
                </BootStrapModal>


            </Container>

            <style jsx>
                {`
                  .b-example-divider {
                    height: 3rem;
                    background-color: rgba(0, 0, 0, .1);
                    border: solid rgba(0, 0, 0, .15);
                    border-width: 1px 0;
                    box-shadow: inset 0 0.5em 1.5em rgb(0 0 0 / 10%), inset 0 0.125em 0.5em rgb(0 0 0 / 15%);
                  }
                  .card-cover {
                    background-repeat: no-repeat;
                    background-position: center center;
                    background-size: cover;
                }
                
              `}
            </style>

        </>
    )
}

export default About;