import { useEffect, useState } from 'react';
import Head from 'next/head';
import { str_replace } from '../../../helper/php.helper';
import Container from '../../../layouts/deskop/Container';
import BootStrapModal from '../../../elements/modal';
import { base_url } from '../../../helper/site.helper';

function Home(data = {}) {
  useEffect(() => {
    require('bootstrap/dist/js/bootstrap.bundle.min.js');
  }, []);

  return (
    <>
      <Container>
        <Head>
          <title>Home - ArdorNext</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="px-4 pt-5 my-5 text-center border-bottom">
          <h1 className="display-4 fw-bold">Welcome to ArdorNext.</h1>
          <div className="col-lg-6 mx-auto">
            <p className="lead mb-4">
              Quickly design and customize responsive mobile-first sites with
              Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables
              and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript
              plugins.
            </p>
            <div className="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
              <a href={base_url('about')}>
                <button type="button" className="btn btn-outline-secondary btn-lg px-4 me-sm-3">
                  Know More
</button>
              </a>
              <a href={base_url('register')}><button type="button" className="btn btn-primary btn-lg px-4">Create an Account</button></a>
            </div>
          </div>
          <div className="overflow-hidden" style={{ 'maxHeight': '30vh' }}>
            <div className="container px-5">
              <img
                src="/site/images/bootstrap-docs.png"
                className="img-fluid border rounded-3 shadow-lg mb-4"
                alt="Example image"
                width="700"
                height="500"
                loading="lazy"
              />
            </div>
          </div>
        </div>

        <div className="container col-xxl-8 px-4 py-5">
          <div className="row flex-lg-row-reverse align-items-center g-5 py-5">
            <div className="col-10 col-sm-8 col-lg-6">
              <img
                src="/site/images/bootstrap-docs.png"
                className="d-block mx-lg-auto img-fluid"
                alt="Bootstrap Themes"
                width="700"
                height="500"
                loading="lazy"
              />
            </div>
            <div className="col-lg-6">
              <h1 className="display-5 fw-bold lh-1 mb-3">Responsive left-aligned hero with image</h1>
              <p className="lead">
                Quickly design and customize responsive mobile-first sites with
                Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass
                variables and mixins, responsive grid system, extensive prebuilt components, and
                powerful JavaScript plugins.
              </p>
              <div className="d-grid gap-2 d-md-flex justify-content-md-start">
                <button type="button" className="btn btn-primary btn-lg px-4 me-md-2">Primary</button>
                <button type="button" className="btn btn-outline-secondary btn-lg px-4">Default</button>
              </div>
            </div>
          </div>
        </div>
        <div className="container px-4 py-5" id="hanging-icons">
          <h2 className="pb-2 border-bottom">Built for Latest</h2>
          <div className="row g-4 py-5 row-cols-1 row-cols-lg-3">
            <div className="col d-flex align-items-start">
              <div
                className="icon-square text-bg-light d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3"
              />
              <div>
                <h3 className="fs-2">Built for react developers</h3>
                <p>ArdorNext is built to make your life easier. Variables, build tooling, documentation, and reusable components.</p>
              </div>
            </div>
            <div className="col d-flex align-items-start">
              <div
                className="icon-square text-bg-light d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3"
              />
              <div>
                <h3 className="fs-2">Designed to be modern</h3>
                <p>Designed with the latest design trends in mind. Landkit feels modern, minimal, and beautiful.</p>

              </div>
            </div>
            <div className="col d-flex align-items-start">
              <div className="icon-square text-bg-light d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3" />
              <div>
                <h3 className="fs-2">Documentation for everything</h3>
                <p>We've written extensive documentation for components and tools, so you never have to reverse engineer anything.</p>

              </div>
            </div>
          </div>
        </div>
        <div className="border-bottom" />
        <div className="container col-xl-10 col-xxl-8 px-4 py-5">
          <div className="row align-items-center g-lg-5 py-5">
            <div className="col-md-10 mx-auto col-lg-5">
              <h3 className="display-6">Subscribe to Newsletter</h3>
              <form className="p-4 p-md-5 border rounded-3 bg-light">
                <div className="form-floating mb-3">
                  <input
                        type="email"
                        className="form-control"
                        id="floatingInput"
                        placeholder="name@example.com"
                      />
                  <label htmlFor="floatingInput">Email address</label>
                </div>
                <button className="w-100 btn btn-lg btn-primary" type="button">Subscribe Now</button>
              </form>
            </div>
            <div className="col-lg-7 text-center text-lg-start">
              <h3 className="display-5 lh-1 mb-3">
                The most useful resource
                ever created for developers.
              </h3>
              <p className="col-lg-10 fs-4">
                Below is an example form built entirely with Bootstrap’s form
                controls. Each required form group has a validation state that can be triggered by
                attempting to submit the form without completing it.
              </p>
            </div>

          </div>
        </div>
        <div className="border-bottom" />
        <div className="bg-primary text-secondary px-4 py-5 text-center">
          <div className="py-5">
            <h1 className="display-5 fw-bold text-white">We have lots of experience building Bootstrap themes.</h1>
            <div className="col-lg-6 mx-auto">
              <p className="fs-5 mb-4 text-white"> Build a beautiful, modern website with flexible Bootstrap components built from scratch.</p>
              <div className="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <button type="button" className="btn btn-danger text-white btn-lg px-4 me-sm-3">
                  Connect With Us
</button>
                <button type="button" className="btn text-bg-light btn-lg px-4">Download Now</button>
              </div>
            </div>
          </div>
        </div>

        <div className="container px-4 py-5" id="custom-cards">
          <h2 className="pb-2 border-bottom">Custom cards</h2>

          <div className="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
            <div className="col">
              <div
                className="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg"
                style={{ backgroundImage: "url('/site/images/unsplash-photo-3.jpg')" }}
              >
                <div className="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                  <h3 className="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Bootstrap users since the beginning</h3>
                  <ul className="d-flex list-unstyled mt-auto">
                        <li className="me-auto">
                            <img
                                src="https://github.com/twbs.png"
                                alt="Bootstrap"
                                width="32"
                                height="32"
                                className="rounded-circle border border-white"
                              />
                          </li>
                        <li className="d-flex align-items-center me-3">
                            <svg className="bi me-2" width="1em" height="1em" />
                            <small>Earth</small>
                          </li>
                        <li className="d-flex align-items-center">
                            <svg className="bi me-2" width="1em" height="1em" />
                            <small>3d</small>
                          </li>
                      </ul>
                </div>
              </div>
            </div>

            <div className="col">
              <div
                className="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg"
                style={{ backgroundImage: "url('/site/images/unsplash-photo-3.jpg')" }}
              >
                <div className="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                  <h3 className="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Deep understanding of Bootstrap</h3>
                  <ul className="d-flex list-unstyled mt-auto">
                        <li className="me-auto">
                            <img
                                src="https://github.com/twbs.png"
                                alt="Bootstrap"
                                width="32"
                                height="32"
                                className="rounded-circle border border-white"
                              />
                          </li>
                        <li className="d-flex align-items-center me-3">
                            <svg className="bi me-2" width="1em" height="1em" />
                            <small>India</small>
                          </li>
                        <li className="d-flex align-items-center">
                            <svg className="bi me-2" width="1em" height="1em" />
                            <small>4d</small>
                          </li>
                      </ul>
                </div>
              </div>
            </div>

            <div className="col">
              <div
                className="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg"
                style={{ backgroundImage: "url('/site/images/unsplash-photo-3.jpg')" }}
              >
                <div className="d-flex flex-column h-100 p-5 pb-3 text-shadow-1">
                  <h3 className="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Expertise in React.Js</h3>
                  <ul className="d-flex list-unstyled mt-auto">
                        <li className="me-auto">
                            <img
                                src="https://github.com/twbs.png"
                                alt="Bootstrap"
                                width="32"
                                height="32"
                                className="rounded-circle border border-white"
                              />
                          </li>
                        <li className="d-flex align-items-center me-3">
                            <svg className="bi me-2" width="1em" height="1em" />
                            <small>California</small>
                          </li>
                        <li className="d-flex align-items-center">
                            <svg className="bi me-2" width="1em" height="1em" />
                            <small>5d</small>
                          </li>
                      </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        <BootStrapModal modalID="exampleModal" modalTitle="Contact Now Modal" modalAttribute={{ size: 'sm', buttonClass: 'btn btn-primary' }}>
          <form>
            <div className="mb-3">
              <label htmlFor="recipient-name" className="col-form-label">Recipient:</label>
              <input type="text" className="form-control" id="recipient-name" />
            </div>
            <div className="mb-3">
              <label htmlFor="message-text" className="col-form-label">Message:</label>
              <textarea className="form-control" id="message-text" />
            </div>
          </form>
        </BootStrapModal>

      </Container>

      <style jsx>
        {`
                  .b-example-divider {
                    height: 3rem;
                    background-color: rgba(0, 0, 0, .1);
                    border: solid rgba(0, 0, 0, .15);
                    border-width: 1px 0;
                    box-shadow: inset 0 0.5em 1.5em rgb(0 0 0 / 10%), inset 0 0.125em 0.5em rgb(0 0 0 / 15%);
                  }
                  .card-cover {
                    background-repeat: no-repeat;
                    background-position: center center;
                    background-size: cover;
                }
                
              `}
      </style>

    </>
  );
}

export default Home;
